//! UDON Core Parser
//!
//! Streaming, event-based parser for UDON (Universal Document & Object Notation).
//! Generated by descent from udon.desc.
//!
//! # Architecture
//!
//! - **parser.rs** - Generated recursive descent parser (callback-based)
//! - **span.rs** - Span/Location types
//! - **value.rs** - Scalar value type parsing (post-hoc classifier)

pub mod parser;
pub mod span;
pub mod value;

pub use parser::*;
pub use span::{Location, Span};
pub use value::Value;
