//! UDON Parser - Generated by genmachine
//!
//! This is a generated file. Do not edit directly.
//! Source: udon.machine

use crate::event::Event;
use crate::span::Span;
use memchr::{memchr, memchr3};

/// Stack entry for tracking element hierarchy.
#[derive(Debug, Clone, Copy)]
struct StackEntry {
    /// Column where the element started (0-indexed)
    base_column: u16,
    /// Byte offset where element started (for ElementEnd span)
    span_start: u32,
}

/// Parser state for streaming UDON parsing.
///
/// The lifetime `'a` refers to the source buffer - all parsed content
/// is zero-copy slices into the original input.
pub struct Parser<'a> {
    input: &'a [u8],
    pos: usize,
    line: u32,
    column: u32,
    line_start: usize,

    /// Accumulator start position (for MARK/TERM pattern)
    mark_start: usize,

    /// Element stack for indent/dedent tracking
    element_stack: Vec<StackEntry>,

    /// Pending events to return
    events: Vec<Event<'a>>,
}

impl<'a> Parser<'a> {
    /// Create a new parser for the given input.
    #[inline]
    pub fn new(input: &'a [u8]) -> Self {
        // Pre-allocate based on input size heuristic:
        // ~1 event per 50 bytes is a reasonable estimate
        let event_capacity = (input.len() / 50).max(16);
        let stack_capacity = 16; // Typical nesting depth

        Self {
            input,
            pos: 0,
            line: 1,
            column: 1,
            line_start: 0,
            mark_start: 0,
            element_stack: Vec::with_capacity(stack_capacity),
            events: Vec::with_capacity(event_capacity),
        }
    }

    /// Flush remaining elements at end of input.
    fn flush_stack(&mut self) {
        while let Some(entry) = self.element_stack.pop() {
            self.emit(Event::ElementEnd {
                span: Span::new(entry.span_start as usize, self.pos),
            });
        }
    }

    /// Parse the entire input and return all events.
    pub fn parse(&mut self) -> Vec<Event<'a>> {
        self.parse_document();
        self.flush_stack();
        std::mem::take(&mut self.events)
    }

    /// Handle start of a new line - count indent and pop stack as needed.
    /// Returns the column where content starts, or None if we hit EOF/error.
    fn handle_line_start(&mut self) -> Option<u16> {
        // Count leading spaces (error on tab)
        while let Some(b) = self.peek() {
            match b {
                b' ' => self.advance(),
                b'\t' => {
                    self.emit(Event::Error {
                        message: "Tabs are not allowed in UDON indentation",
                        span: Span::new(self.pos, self.pos + 1),
                    });
                    self.advance();
                    // Continue parsing despite error
                }
                _ => break,
            }
        }

        // Get the column where actual content starts
        let content_column = (self.column - 1) as u16; // 0-indexed

        // Pop stack while content_column <= top.base_column
        while let Some(entry) = self.element_stack.last().copied() {
            if content_column <= entry.base_column {
                self.element_stack.pop();
                self.emit(Event::ElementEnd {
                    span: Span::new(entry.span_start as usize, self.pos),
                });
            } else {
                break;
            }
        }

        Some(content_column)
    }

    /// Push an element onto the stack with its column position.
    fn push_element(&mut self, column: u16) {
        self.element_stack.push(StackEntry {
            base_column: column,
            span_start: self.pos as u32,
        });
    }

    /// Check if we've reached end of input.
    #[inline]
    fn eof(&self) -> bool {
        self.pos >= self.input.len()
    }

    /// Get current byte without advancing.
    #[inline]
    fn peek(&self) -> Option<u8> {
        self.input.get(self.pos).copied()
    }

    /// Advance one byte (handles line/column tracking).
    #[inline]
    fn advance(&mut self) {
        if let Some(b) = self.input.get(self.pos) {
            if *b == b'\n' {
                self.line += 1;
                self.column = 1;
                self.pos += 1;
                self.line_start = self.pos;
            } else {
                self.column += 1;
                self.pos += 1;
            }
        }
    }

    /// Mark the current position for accumulation.
    #[inline]
    fn mark(&mut self) {
        self.mark_start = self.pos;
    }

    /// Get the accumulated slice from mark to current position.
    #[inline]
    fn term(&self) -> &'a [u8] {
        &self.input[self.mark_start..self.pos]
    }

    /// Get the current column (0-indexed) based on line_start.
    /// This is the actual column in the source, not a tracked variable.
    #[inline]
    fn current_column(&self) -> i32 {
        (self.pos - self.line_start) as i32
    }

    /// Create a span from mark to current position.
    #[inline]
    fn span_from_mark(&self) -> Span {
        Span::new(self.mark_start, self.pos)
    }

    /// Emit an event.
    #[inline]
    fn emit(&mut self, event: Event<'a>) {
        self.events.push(event);
    }

    // ========== Fast Scanning (memchr-accelerated) ==========

    /// Scan forward until we hit one of the target bytes or EOF.
    /// Updates position but NOT line/column (caller must handle).
    /// Returns the byte found, or None if EOF.
    #[inline]
    fn scan_to(&mut self, needle: u8) -> Option<u8> {
        if let Some(offset) = memchr(needle, &self.input[self.pos..]) {
            self.pos += offset;
            Some(needle)
        } else {
            self.pos = self.input.len();
            None
        }
    }

    /// Scan forward until we hit one of three target bytes or EOF.
    #[inline]
    fn scan_to3(&mut self, a: u8, b: u8, c: u8) -> Option<u8> {
        if let Some(offset) = memchr3(a, b, c, &self.input[self.pos..]) {
            self.pos += offset;
            Some(self.input[self.pos])
        } else {
            self.pos = self.input.len();
            None
        }
    }

    // ========== Hand-written Helpers ==========

    /// Check if byte can start a LABEL (Unicode letter or underscore).
    /// LABEL = [\p{L}_][\p{L}\p{N}_-]*
    #[inline]
    fn is_label_start(&self, b: u8) -> bool {
        // Fast path for ASCII
        matches!(b, b'a'..=b'z' | b'A'..=b'Z' | b'_') ||
        // For non-ASCII, need to check Unicode - defer to full check
        (b >= 0x80 && self.is_unicode_letter_at(self.pos))
    }

    /// Check if byte can continue a LABEL.
    #[inline]
    fn is_label_continue(&self, b: u8) -> bool {
        matches!(b, b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'_' | b'-') ||
        (b >= 0x80 && self.is_unicode_letter_or_number_at(self.pos))
    }

    /// Check if position starts a Unicode letter (for non-ASCII).
    fn is_unicode_letter_at(&self, pos: usize) -> bool {
        // Decode UTF-8 and check if it's a Unicode letter
        if let Some(slice) = self.input.get(pos..) {
            if let Ok(s) = std::str::from_utf8(slice) {
                if let Some(c) = s.chars().next() {
                    return unicode_xid::UnicodeXID::is_xid_start(c);
                }
            }
        }
        false
    }

    /// Check if position is a Unicode letter or number (for non-ASCII).
    fn is_unicode_letter_or_number_at(&self, pos: usize) -> bool {
        if let Some(slice) = self.input.get(pos..) {
            if let Ok(s) = std::str::from_utf8(slice) {
                if let Some(c) = s.chars().next() {
                    return unicode_xid::UnicodeXID::is_xid_continue(c);
                }
            }
        }
        false
    }

    /// Scan a LABEL starting at current position.
    /// Returns the label slice and advances past it.
    fn scan_label(&mut self) -> Option<&'a [u8]> {
        let start = self.pos;

        // First char must be letter or underscore
        if let Some(&b) = self.input.get(self.pos) {
            if !self.is_label_start(b) {
                return None;
            }
            self.advance_bytes(self.char_len_at(self.pos));
        } else {
            return None;
        }

        // Continue with letters, numbers, underscore, hyphen
        while let Some(&b) = self.input.get(self.pos) {
            if self.is_label_continue(b) {
                self.advance_bytes(self.char_len_at(self.pos));
            } else {
                break;
            }
        }

        Some(&self.input[start..self.pos])
    }

    /// Get the byte length of the UTF-8 character at position.
    #[inline]
    fn char_len_at(&self, pos: usize) -> usize {
        match self.input.get(pos) {
            Some(&b) if b < 0x80 => 1,
            Some(&b) if b < 0xE0 => 2,
            Some(&b) if b < 0xF0 => 3,
            Some(&b) if b < 0xF8 => 4,
            _ => 1,
        }
    }

    /// Advance by a specific number of bytes.
    #[inline]
    fn advance_bytes(&mut self, n: usize) {
        for _ in 0..n {
            self.advance();
        }
    }

    /// Check if current position could start an element.
    /// Element starters: Unicode letter, '[', '.', '{', "'"
    #[inline]
    fn is_element_start(&self) -> bool {
        match self.peek() {
            Some(b'[') | Some(b'.') | Some(b'{') | Some(b'\'') => true,
            Some(b) => self.is_label_start(b),
            None => false,
        }
    }

    /// Check if a byte could start an element (for match guards).
    #[inline]
    fn is_element_start_byte(&self, b: u8) -> bool {
        matches!(b, b'[' | b'.' | b'{' | b'\'') || self.is_label_start(b)
    }

    /// Parse an optional suffix modifier (?, !, *, +).
    fn parse_suffix(&mut self) -> Option<char> {
        match self.peek() {
            Some(b'?') => { self.advance(); Some('?') }
            Some(b'!') => { self.advance(); Some('!') }
            Some(b'*') => { self.advance(); Some('*') }
            Some(b'+') => { self.advance(); Some('+') }
            _ => None,
        }
    }

    // ========== Value Emission Helpers ==========
    // Note: Element identity and attribute parsing is now expressed in the DSL.
    // These are minimal helpers for typed value emission.

    /// Emit a typed value based on the current term content.
    /// Uses syntactic typing to determine Int, Float, Bool, Nil, or String.
    fn emit_typed_value(&mut self) {
        let bytes = self.term();
        let span = self.span_from_mark();

        // Check for nil
        if bytes == b"null" || bytes == b"nil" || bytes == b"~" {
            self.emit(Event::NilValue { span });
            return;
        }

        // Check for bool
        if bytes == b"true" {
            self.emit(Event::BoolValue { value: true, span });
            return;
        }
        if bytes == b"false" {
            self.emit(Event::BoolValue { value: false, span });
            return;
        }

        // Try to parse as number
        if let Some(event) = self.try_parse_number_event(bytes, span) {
            self.emit(event);
            return;
        }

        // Default to string
        self.emit(Event::StringValue { value: bytes, span });
    }

    /// Try to parse bytes as a numeric value and return the appropriate event.
    fn try_parse_number_event(&self, bytes: &'a [u8], span: Span) -> Option<Event<'a>> {
        use crate::Value;
        match Value::parse(bytes) {
            Value::Integer(i) => Some(Event::IntegerValue { value: i, span }),
            Value::Float(f) => Some(Event::FloatValue { value: f, span }),
            Value::Rational { numerator, denominator } => {
                Some(Event::RationalValue { numerator, denominator, span })
            }
            Value::Complex { real, imag } => {
                Some(Event::ComplexValue { real, imag, span })
            }
            _ => None, // Not a number
        }
    }

    // Note: parse_indented_attribute and parse_array_contents are now
    // expressed in the DSL (udon.machine). See :attr_* and :array_* states.
    // ========== Generated State Machine ==========


    fn parse_document(&mut self) {
        let mut col: i32 = 0;

        #[derive(Clone, Copy)]
        enum State { SStart, SEscaped, SEscapedText, SProse, SCheckInlineComment, SInlineComment, SInlineCommentNested, SLineComment, SBlockComment, SMaybeFreeform, SMaybeFreeform2, SFreeform, SFreeformEnd1, SFreeformEnd2, SDirective, SDirectiveInterp, SDirectiveName, SDirectiveBody, SProseAfterDirective, SSkipLine }

        let mut state = State::SStart;
        loop {
            match state {
                State::SStart => {
                    if self.eof() {
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.advance();
                            col = 0;
                            state = State::SStart;
                        }
                        b' ' => {
                            self.advance();
                            col += 1;
                            state = State::SStart;
                        }
                        b'\t' => {
                            self.advance();
                            self.emit(Event::Error { message: "no tabs", span: Span::new(self.pos, self.pos) });
                            state = State::SSkipLine;
                        }
                        b'\'' => {
                            self.advance();
                            state = State::SEscaped;
                        }
                        b';' => {
                            self.advance();
                            self.mark();
                            state = State::SBlockComment;
                        }
                        b'|' => {
                            self.advance();
                            self.parse_element(self.current_column());
                            state = State::SStart;
                        }
                        b'`' => {
                            self.advance();
                            state = State::SMaybeFreeform;
                        }
                        b'!' => {
                            self.advance();
                            state = State::SDirective;
                        }
                        _ => {
                            self.mark();
                            state = State::SProse;
                        }
                    }
                }
                State::SEscaped => {
                    if self.eof() {
                        self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            col = 0;
                            state = State::SStart;
                        }
                        _ => {
                            self.mark();
                            state = State::SEscapedText;
                        }
                    }
                }
                State::SEscapedText => {
                    if self.eof() {
                        self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            col = 0;
                            state = State::SStart;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SProse => {
                    if self.eof() {
                        self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            col = 0;
                            state = State::SStart;
                        }
                        b';' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SCheckInlineComment;
                        }
                        b'|' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            self.parse_element(self.current_column());
                            state = State::SStart;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SCheckInlineComment => {
                    match self.peek().unwrap() {
                        b'{' => {
                            self.advance();
                            state = State::SInlineComment;
                        }
                        _ => {
                            self.mark();
                            state = State::SLineComment;
                        }
                    }
                }
                State::SInlineComment => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed comment", span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'}' => {
                            self.advance();
                            state = State::SProse;
                        }
                        b'{' => {
                            self.advance();
                            state = State::SInlineCommentNested;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SInlineCommentNested => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed comment", span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'}' => {
                            self.advance();
                            state = State::SInlineComment;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SLineComment => {
                    if self.eof() {
                        self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                            col = 0;
                            state = State::SStart;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SBlockComment => {
                    if self.eof() {
                        self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                            col = 0;
                            state = State::SStart;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SMaybeFreeform => {
                    match self.peek().unwrap() {
                        b'`' => {
                            self.advance();
                            state = State::SMaybeFreeform2;
                        }
                        _ => {
                            self.mark();
                            state = State::SProse;
                        }
                    }
                }
                State::SMaybeFreeform2 => {
                    match self.peek().unwrap() {
                        b'`' => {
                            self.mark();
                            state = State::SFreeform;
                        }
                        _ => {
                            self.mark();
                            state = State::SProse;
                        }
                    }
                }
                State::SFreeform => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed freeform", span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'`' => {
                            self.advance();
                            state = State::SFreeformEnd1;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SFreeformEnd1 => {
                    match self.peek().unwrap() {
                        b'`' => {
                            self.advance();
                            state = State::SFreeformEnd2;
                        }
                        _ => {
                            self.advance();
                            state = State::SFreeform;
                        }
                    }
                }
                State::SFreeformEnd2 => {
                    match self.peek().unwrap() {
                        b'`' => {
                            self.emit(Event::RawContent { content: self.term(), span: self.span_from_mark() });
                            col = 0;
                            state = State::SStart;
                        }
                        _ => {
                            self.advance();
                            state = State::SFreeform;
                        }
                    }
                }
                State::SDirective => {
                    if self.eof() {
                        self.emit(Event::Error { message: "incomplete directive", span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'{' => {
                            self.mark();
                            state = State::SDirectiveInterp;
                        }
                        _ => {
                            self.mark();
                            state = State::SDirectiveName;
                        }
                    }
                }
                State::SDirectiveInterp => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed directive", span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'}' => {
                            self.emit(Event::Interpolation { expression: self.term(), span: self.span_from_mark() });
                            state = State::SProseAfterDirective;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SDirectiveName => {
                    if self.eof() {
                        // TODO: emit Directive
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            // TODO: emit Directive
                            col = 0;
                            state = State::SStart;
                        }
                        b'{' => {
                            // TODO: emit Directive
                            state = State::SDirectiveBody;
                        }
                        b' ' | b'\t' => {
                            // TODO: emit Directive
                            state = State::SProseAfterDirective;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SDirectiveBody => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed directive", span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'}' => {
                            // TODO: emit DirectiveBody
                            state = State::SProseAfterDirective;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SProseAfterDirective => {
                    if self.eof() {
                        self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            col = 0;
                            state = State::SStart;
                        }
                        b';' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SCheckInlineComment;
                        }
                        b'|' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            self.parse_element(self.current_column());
                            state = State::SStart;
                        }
                        _ => {
                            self.mark();
                            state = State::SProse;
                        }
                    }
                }
                State::SSkipLine => {
                    if self.eof() {
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            col = 0;
                            state = State::SStart;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
            }
        }
    }

    fn parse_element(&mut self, elem_col: i32) {
        let mut col: i32 = elem_col;
        let mut content_base: i32 = -1;

        #[derive(Clone, Copy)]
        enum State { SIdentity, SIdName, SIdAfterName, SIdCheckBracket, SIdBracketStart, SIdAnonBracket, SIdBracketValue, SIdAfterBracket, SIdCheckClass, SIdClassStart, SIdClassName, SIdClassCheckMore, SIdSpaceSuffix, SIdQuotedName, SIdQuotedNameContent, SIdQuotedNameEscape, SIdClassQuoted, SIdClassQuotedContent, SIdClassQuotedEscape, SIdCheckMore, SAfterIdentity, SInlineContent, SInlineText, SElemCommentCheck, SElemInlineComment, SElemLineComment, SChildren, SChildrenContent, SChildrenAfterElement, SChildrenCountWs, SChildEscaped, SChildEscapedText, SChildProse, SChildCommentCheck, SChildInlineComment, SChildLineComment, SChildBlockComment, SChildFreeformCheck, SChildFreeformCheck2, SChildFreeform, SChildFreeformEnd1, SChildFreeformEnd2, SChildDirective, SChildDirectiveInterp, SChildDirectiveName, SChildDirectiveBody, SSkipChild, SAttrKey, SAttrKeyScan, SAttrKeyQuoted, SAttrKeyQuotedContent, SAttrKeyQuotedEsc, SAttrWs, SAttrValue, SAttrComment, SAttrDquote, SAttrDquoteContent, SAttrDquoteEsc, SAttrSquote, SAttrSquoteContent, SAttrSquoteEsc, SAttrBare, SAttrAfterValue, SAttrSkipLine, SArrayValue, SArrDquote, SArrDquoteContent, SArrDquoteEsc, SArrSquote, SArrSquoteContent, SArrSquoteEsc, SArrBare }

        let mut state = State::SIdentity;
        loop {
            match state {
                State::SIdentity => {
                    match self.peek().unwrap() {
                        b if self.is_label_start(b) => {
                            self.mark();
                            state = State::SIdName;
                        }
                        b'[' => {
                            self.advance();
                            state = State::SIdAnonBracket;
                        }
                        b'.' => {
                            self.emit(Event::ElementStart { name: None, span: Span::new(self.pos, self.pos) });
                            state = State::SIdClassStart;
                        }
                        b'?' => {
                            self.emit(Event::ElementStart { name: None, span: Span::new(self.pos, self.pos) });
                            self.emit(Event::Attribute { key: b"?", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            state = State::SIdCheckMore;
                        }
                        b'!' => {
                            self.emit(Event::ElementStart { name: None, span: Span::new(self.pos, self.pos) });
                            self.emit(Event::Attribute { key: b"!", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            state = State::SIdCheckMore;
                        }
                        b'*' => {
                            self.emit(Event::ElementStart { name: None, span: Span::new(self.pos, self.pos) });
                            self.emit(Event::Attribute { key: b"*", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            state = State::SIdCheckMore;
                        }
                        b'+' => {
                            self.emit(Event::ElementStart { name: None, span: Span::new(self.pos, self.pos) });
                            self.emit(Event::Attribute { key: b"+", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            state = State::SIdCheckMore;
                        }
                        b'\'' => {
                            self.advance();
                            state = State::SIdQuotedName;
                        }
                        _ => {
                            self.emit(Event::ElementStart { name: None, span: Span::new(self.pos, self.pos) });
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SIdName => {
                    match self.peek().unwrap() {
                        b if self.is_label_continue(b) => {
                            self.advance();
                        }
                        _ => {
                            self.emit(Event::ElementStart { name: Some(self.term()), span: self.span_from_mark() });
                            state = State::SIdAfterName;
                        }
                    }
                }
                State::SIdAfterName => {
                    match self.peek().unwrap() {
                        b'?' => {
                            self.emit(Event::Attribute { key: b"?", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SIdCheckBracket;
                        }
                        b'!' => {
                            self.emit(Event::Attribute { key: b"!", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SIdCheckBracket;
                        }
                        b'*' => {
                            self.emit(Event::Attribute { key: b"*", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SIdCheckBracket;
                        }
                        b'+' => {
                            self.emit(Event::Attribute { key: b"+", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SIdCheckBracket;
                        }
                        b'[' => {
                            self.advance();
                            state = State::SIdBracketStart;
                        }
                        b'.' => {
                            self.advance();
                            state = State::SIdClassStart;
                        }
                        _ => {
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SIdCheckBracket => {
                    match self.peek().unwrap() {
                        b'[' => {
                            self.advance();
                            state = State::SIdBracketStart;
                        }
                        b'.' => {
                            self.advance();
                            state = State::SIdClassStart;
                        }
                        _ => {
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SIdBracketStart => {
                    match self.peek().unwrap() {
                        b']' => {
                            self.advance();
                            state = State::SIdAfterBracket;
                        }
                        _ => {
                            self.emit(Event::Attribute { key: b"$id", span: self.span_from_mark() });
                            self.mark();
                            state = State::SIdBracketValue;
                        }
                    }
                }
                State::SIdAnonBracket => {
                    match self.peek().unwrap() {
                        b']' => {
                            self.emit(Event::ElementStart { name: None, span: Span::new(self.pos, self.pos) });
                            state = State::SIdAfterBracket;
                        }
                        _ => {
                            self.emit(Event::ElementStart { name: None, span: Span::new(self.pos, self.pos) });
                            self.emit(Event::Attribute { key: b"$id", span: self.span_from_mark() });
                            self.mark();
                            state = State::SIdBracketValue;
                        }
                    }
                }
                State::SIdBracketValue => {
                    match self.peek().unwrap() {
                        b']' => {
                            self.emit(Event::StringValue { value: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SIdAfterBracket;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SIdAfterBracket => {
                    match self.peek().unwrap() {
                        b'?' => {
                            self.emit(Event::Attribute { key: b"?", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SIdCheckClass;
                        }
                        b'!' => {
                            self.emit(Event::Attribute { key: b"!", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SIdCheckClass;
                        }
                        b'*' => {
                            self.emit(Event::Attribute { key: b"*", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SIdCheckClass;
                        }
                        b'+' => {
                            self.emit(Event::Attribute { key: b"+", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SIdCheckClass;
                        }
                        b'.' => {
                            self.advance();
                            state = State::SIdClassStart;
                        }
                        _ => {
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SIdCheckClass => {
                    match self.peek().unwrap() {
                        b'.' => {
                            self.advance();
                            state = State::SIdClassStart;
                        }
                        _ => {
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SIdClassStart => {
                    match self.peek().unwrap() {
                        b if self.is_label_start(b) => {
                            self.emit(Event::Attribute { key: b"$class", span: self.span_from_mark() });
                            self.mark();
                            state = State::SIdClassName;
                        }
                        b'\'' => {
                            self.emit(Event::Attribute { key: b"$class", span: self.span_from_mark() });
                            state = State::SIdClassQuoted;
                        }
                        _ => {
                            self.emit(Event::Error { message: "expected class name", span: Span::new(self.pos, self.pos) });
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SIdClassName => {
                    match self.peek().unwrap() {
                        b if self.is_label_continue(b) => {
                            self.advance();
                        }
                        _ => {
                            self.emit(Event::StringValue { value: self.term(), span: self.span_from_mark() });
                            state = State::SIdClassCheckMore;
                        }
                    }
                }
                State::SIdClassCheckMore => {
                    match self.peek().unwrap() {
                        b'.' => {
                            self.advance();
                            state = State::SIdClassStart;
                        }
                        b' ' => {
                            self.advance();
                            state = State::SIdSpaceSuffix;
                        }
                        _ => {
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SIdSpaceSuffix => {
                    match self.peek().unwrap() {
                        b'?' => {
                            self.emit(Event::Attribute { key: b"?", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SAfterIdentity;
                        }
                        b'!' => {
                            self.emit(Event::Attribute { key: b"!", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SAfterIdentity;
                        }
                        b'*' => {
                            self.emit(Event::Attribute { key: b"*", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SAfterIdentity;
                        }
                        b'+' => {
                            self.emit(Event::Attribute { key: b"+", span: self.span_from_mark() });
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            self.advance();
                            state = State::SAfterIdentity;
                        }
                        b' ' => {
                            self.advance();
                        }
                        _ => {
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SIdQuotedName => {
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.emit(Event::ElementStart { name: Some(self.term()), span: self.span_from_mark() });
                            state = State::SIdAfterName;
                        }
                        _ => {
                            self.mark();
                            state = State::SIdQuotedNameContent;
                        }
                    }
                }
                State::SIdQuotedNameContent => {
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.emit(Event::ElementStart { name: Some(self.term()), span: self.span_from_mark() });
                            state = State::SIdAfterName;
                        }
                        b'\\' => {
                            self.advance();
                            state = State::SIdQuotedNameEscape;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SIdQuotedNameEscape => {
                    match self.peek().unwrap() {
                        _ => {
                            self.advance();
                            state = State::SIdQuotedNameContent;
                        }
                    }
                }
                State::SIdClassQuoted => {
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.mark();
                            state = State::SIdClassQuotedContent;
                        }
                        _ => {
                            self.emit(Event::Error { message: "expected quote", span: Span::new(self.pos, self.pos) });
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SIdClassQuotedContent => {
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.emit(Event::QuotedStringValue { value: self.term(), span: self.span_from_mark() });
                            state = State::SIdClassCheckMore;
                        }
                        b'\\' => {
                            self.advance();
                            state = State::SIdClassQuotedEscape;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SIdClassQuotedEscape => {
                    match self.peek().unwrap() {
                        _ => {
                            self.advance();
                            state = State::SIdClassQuotedContent;
                        }
                    }
                }
                State::SIdCheckMore => {
                    match self.peek().unwrap() {
                        b'[' => {
                            self.advance();
                            state = State::SIdBracketStart;
                        }
                        b'.' => {
                            self.advance();
                            state = State::SIdClassStart;
                        }
                        _ => {
                            state = State::SAfterIdentity;
                        }
                    }
                }
                State::SAfterIdentity => {
                    if self.eof() {
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        b' ' | b'\t' => {
                            self.advance();
                            col += 1;
                            state = State::SInlineContent;
                        }
                        b';' => {
                            self.advance();
                            state = State::SElemCommentCheck;
                        }
                        b'|' => {
                            self.advance();
                            self.parse_element(self.current_column());
                            state = State::SInlineContent;
                        }
                        _ => {
                            self.mark();
                            state = State::SInlineText;
                        }
                    }
                }
                State::SInlineContent => {
                    if self.eof() {
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        b';' => {
                            self.advance();
                            state = State::SElemCommentCheck;
                        }
                        b'|' => {
                            self.advance();
                            self.parse_element(self.current_column());
                            state = State::SInlineContent;
                        }
                        _ => {
                            self.mark();
                            state = State::SInlineText;
                        }
                    }
                }
                State::SInlineText => {
                    if self.eof() {
                        self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        b';' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SElemCommentCheck;
                        }
                        b'|' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            self.parse_element(self.current_column());
                            state = State::SInlineContent;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SElemCommentCheck => {
                    match self.peek().unwrap() {
                        b'{' => {
                            self.advance();
                            state = State::SElemInlineComment;
                        }
                        _ => {
                            self.mark();
                            state = State::SElemLineComment;
                        }
                    }
                }
                State::SElemInlineComment => {
                    if self.eof() {
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'}' => {
                            self.advance();
                            state = State::SInlineContent;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SElemLineComment => {
                    if self.eof() {
                        self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SChildren => {
                    if self.eof() {
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        b' ' => {
                            self.advance();
                            col += 1;
                            state = State::SChildren;
                        }
                        b'\t' => {
                            self.advance();
                            self.emit(Event::Error { message: "no tabs", span: Span::new(self.pos, self.pos) });
                            state = State::SSkipChild;
                        }
                        _ => {
                            state = State::SChildrenContent;
                        }
                    }
                }
                State::SChildrenContent => {
                    if self.current_column()  <=  elem_col {
    self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
    return;
}
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.advance();
                            state = State::SChildEscaped;
                        }
                        b';' => {
                            self.advance();
                            self.mark();
                            state = State::SChildBlockComment;
                        }
                        b'|' => {
                            self.advance();
                            self.parse_element(self.current_column());
                            state = State::SChildrenAfterElement;
                        }
                        b':' => {
                            self.advance();
                            state = State::SAttrKey;
                        }
                        b'`' => {
                            self.advance();
                            state = State::SChildFreeformCheck;
                        }
                        b'!' => {
                            self.advance();
                            state = State::SChildDirective;
                        }
                        _ => {
                            self.mark();
                            state = State::SChildProse;
                        }
                    }
                }
                State::SChildrenAfterElement => {
                    if self.eof() {
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        b' ' => {
                            self.advance();
                            col = 1;
                            state = State::SChildrenCountWs;
                        }
                        b'\t' => {
                            self.advance();
                            self.emit(Event::Error { message: "no tabs", span: Span::new(self.pos, self.pos) });
                            state = State::SSkipChild;
                        }
                        _ => {
                            col = 0;
                            state = State::SChildrenContent;
                        }
                    }
                }
                State::SChildrenCountWs => {
                    if self.eof() {
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        b' ' => {
                            self.advance();
                            col += 1;
                            state = State::SChildrenCountWs;
                        }
                        b'\t' => {
                            self.advance();
                            self.emit(Event::Error { message: "no tabs", span: Span::new(self.pos, self.pos) });
                            state = State::SSkipChild;
                        }
                        _ => {
                            state = State::SChildrenContent;
                        }
                    }
                }
                State::SChildEscaped => {
                    if self.eof() {
                        self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        _ => {
                            self.mark();
                            state = State::SChildEscapedText;
                        }
                    }
                }
                State::SChildEscapedText => {
                    if self.eof() {
                        self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SChildProse => {
                    if self.eof() {
                        self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        b';' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SChildCommentCheck;
                        }
                        b'|' => {
                            self.emit(Event::Text { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            self.parse_element(self.current_column());
                            state = State::SChildrenAfterElement;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SChildCommentCheck => {
                    match self.peek().unwrap() {
                        b'{' => {
                            self.advance();
                            state = State::SChildInlineComment;
                        }
                        _ => {
                            self.mark();
                            state = State::SChildLineComment;
                        }
                    }
                }
                State::SChildInlineComment => {
                    if self.eof() {
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'}' => {
                            self.advance();
                            state = State::SChildProse;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SChildLineComment => {
                    if self.eof() {
                        self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SChildBlockComment => {
                    if self.eof() {
                        self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::Comment { content: self.term(), span: self.span_from_mark() });
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SChildFreeformCheck => {
                    match self.peek().unwrap() {
                        b'`' => {
                            self.advance();
                            state = State::SChildFreeformCheck2;
                        }
                        _ => {
                            self.mark();
                            state = State::SChildProse;
                        }
                    }
                }
                State::SChildFreeformCheck2 => {
                    match self.peek().unwrap() {
                        b'`' => {
                            self.mark();
                            state = State::SChildFreeform;
                        }
                        _ => {
                            self.mark();
                            state = State::SChildProse;
                        }
                    }
                }
                State::SChildFreeform => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed freeform", span: Span::new(self.pos, self.pos) });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'`' => {
                            self.advance();
                            state = State::SChildFreeformEnd1;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SChildFreeformEnd1 => {
                    match self.peek().unwrap() {
                        b'`' => {
                            self.advance();
                            state = State::SChildFreeformEnd2;
                        }
                        _ => {
                            self.advance();
                            state = State::SChildFreeform;
                        }
                    }
                }
                State::SChildFreeformEnd2 => {
                    match self.peek().unwrap() {
                        b'`' => {
                            self.emit(Event::RawContent { content: self.term(), span: self.span_from_mark() });
                            col = 0;
                            state = State::SChildren;
                        }
                        _ => {
                            self.advance();
                            state = State::SChildFreeform;
                        }
                    }
                }
                State::SChildDirective => {
                    if self.eof() {
                        // TODO: emit Directive
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'{' => {
                            self.mark();
                            state = State::SChildDirectiveInterp;
                        }
                        _ => {
                            self.mark();
                            state = State::SChildDirectiveName;
                        }
                    }
                }
                State::SChildDirectiveInterp => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed", span: Span::new(self.pos, self.pos) });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'}' => {
                            self.emit(Event::Interpolation { expression: self.term(), span: self.span_from_mark() });
                            state = State::SChildProse;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SChildDirectiveName => {
                    if self.eof() {
                        // TODO: emit Directive
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            // TODO: emit Directive
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        b'{' => {
                            // TODO: emit Directive
                            state = State::SChildDirectiveBody;
                        }
                        b' ' | b'\t' => {
                            // TODO: emit Directive
                            state = State::SChildProse;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SChildDirectiveBody => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed", span: Span::new(self.pos, self.pos) });
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'}' => {
                            // TODO: emit DirectiveBody
                            state = State::SChildProse;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SSkipChild => {
                    if self.eof() {
                        self.emit(Event::ElementEnd { span: Span::new(self.pos, self.pos) });
                        return;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.advance();
                            col = 0;
                            state = State::SChildren;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SAttrKey => {
                    match self.peek().unwrap() {
                        b if self.is_label_start(b) => {
                            self.mark();
                            state = State::SAttrKeyScan;
                        }
                        b'\'' => {
                            self.advance();
                            state = State::SAttrKeyQuoted;
                        }
                        _ => {
                            self.emit(Event::Error { message: "expected attr key", span: Span::new(self.pos, self.pos) });
                            state = State::SChildren;
                        }
                    }
                }
                State::SAttrKeyScan => {
                    match self.peek().unwrap() {
                        b if self.is_label_continue(b) => {
                            self.advance();
                        }
                        _ => {
                            self.emit(Event::Attribute { key: self.term(), span: self.span_from_mark() });
                            state = State::SAttrWs;
                        }
                    }
                }
                State::SAttrKeyQuoted => {
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.mark();
                            state = State::SAttrKeyQuotedContent;
                        }
                        _ => {
                            self.emit(Event::Error { message: "expected quote", span: Span::new(self.pos, self.pos) });
                            state = State::SChildren;
                        }
                    }
                }
                State::SAttrKeyQuotedContent => {
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.emit(Event::Attribute { key: self.term(), span: self.span_from_mark() });
                            state = State::SAttrWs;
                        }
                        b'\\' => {
                            self.advance();
                            state = State::SAttrKeyQuotedEsc;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SAttrKeyQuotedEsc => {
                    match self.peek().unwrap() {
                        _ => {
                            self.advance();
                            state = State::SAttrKeyQuotedContent;
                        }
                    }
                }
                State::SAttrWs => {
                    match self.peek().unwrap() {
                        b' ' | b'\t' => {
                            self.advance();
                        }
                        _ => {
                            state = State::SAttrValue;
                        }
                    }
                }
                State::SAttrValue => {
                    if self.eof() {
                        self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            col = 0;
                            state = State::SChildren;
                        }
                        b';' => {
                            self.emit(Event::BoolValue { value: true, span: self.span_from_mark() });
                            state = State::SAttrComment;
                        }
                        b'[' => {
                            self.emit(Event::ArrayStart { span: Span::new(self.pos, self.pos) });
                            self.advance();
                            state = State::SArrayValue;
                        }
                        b'"' => {
                            self.advance();
                            state = State::SAttrDquote;
                        }
                        b'\'' => {
                            self.advance();
                            state = State::SAttrSquote;
                        }
                        _ => {
                            self.mark();
                            state = State::SAttrBare;
                        }
                    }
                }
                State::SAttrComment => {
                    if self.eof() {
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            col = 0;
                            state = State::SChildren;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SAttrDquote => {
                    match self.peek().unwrap() {
                        b'"' => {
                            self.mark();
                            state = State::SAttrDquoteContent;
                        }
                        _ => {
                            self.emit(Event::Error { message: "expected quote", span: Span::new(self.pos, self.pos) });
                            state = State::SChildren;
                        }
                    }
                }
                State::SAttrDquoteContent => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed string", span: Span::new(self.pos, self.pos) });
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b'"' => {
                            self.emit(Event::QuotedStringValue { value: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SAttrAfterValue;
                        }
                        b'\\' => {
                            self.advance();
                            state = State::SAttrDquoteEsc;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SAttrDquoteEsc => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed string", span: Span::new(self.pos, self.pos) });
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        _ => {
                            self.advance();
                            state = State::SAttrDquoteContent;
                        }
                    }
                }
                State::SAttrSquote => {
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.mark();
                            state = State::SAttrSquoteContent;
                        }
                        _ => {
                            self.emit(Event::Error { message: "expected quote", span: Span::new(self.pos, self.pos) });
                            state = State::SChildren;
                        }
                    }
                }
                State::SAttrSquoteContent => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed string", span: Span::new(self.pos, self.pos) });
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.emit(Event::QuotedStringValue { value: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SAttrAfterValue;
                        }
                        b'\\' => {
                            self.advance();
                            state = State::SAttrSquoteEsc;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SAttrSquoteEsc => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed string", span: Span::new(self.pos, self.pos) });
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        _ => {
                            self.advance();
                            state = State::SAttrSquoteContent;
                        }
                    }
                }
                State::SAttrBare => {
                    if self.eof() {
                        self.emit_typed_value();
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            self.emit_typed_value();
                            col = 0;
                            state = State::SChildren;
                        }
                        b';' => {
                            self.emit_typed_value();
                            state = State::SAttrComment;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SAttrAfterValue => {
                    if self.eof() {
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            col = 0;
                            state = State::SChildren;
                        }
                        b';' => {
                            state = State::SAttrComment;
                        }
                        b' ' | b'\t' => {
                            self.advance();
                        }
                        _ => {
                            self.emit(Event::Error { message: "unexpected after value", span: Span::new(self.pos, self.pos) });
                            state = State::SAttrSkipLine;
                        }
                    }
                }
                State::SAttrSkipLine => {
                    if self.eof() {
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b'\n' => {
                            col = 0;
                            state = State::SChildren;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SArrayValue => {
                    match self.peek().unwrap() {
                        b' ' | b'\t' => {
                            self.advance();
                        }
                        b'\n' => {
                            self.advance();
                        }
                        b']' => {
                            self.emit(Event::ArrayEnd { span: Span::new(self.pos, self.pos) });
                            state = State::SAttrAfterValue;
                        }
                        b'"' => {
                            self.advance();
                            state = State::SArrDquote;
                        }
                        b'\'' => {
                            self.advance();
                            state = State::SArrSquote;
                        }
                        b'[' => {
                            self.emit(Event::ArrayStart { span: Span::new(self.pos, self.pos) });
                            self.advance();
                            state = State::SArrayValue;
                        }
                        _ => {
                            self.mark();
                            state = State::SArrBare;
                        }
                    }
                }
                State::SArrDquote => {
                    match self.peek().unwrap() {
                        b'"' => {
                            self.mark();
                            state = State::SArrDquoteContent;
                        }
                        _ => {
                            self.emit(Event::Error { message: "expected quote", span: Span::new(self.pos, self.pos) });
                            state = State::SArrayValue;
                        }
                    }
                }
                State::SArrDquoteContent => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed string", span: Span::new(self.pos, self.pos) });
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b'"' => {
                            self.emit(Event::QuotedStringValue { value: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SArrayValue;
                        }
                        b'\\' => {
                            self.advance();
                            state = State::SArrDquoteEsc;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SArrDquoteEsc => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed string", span: Span::new(self.pos, self.pos) });
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        _ => {
                            self.advance();
                            state = State::SArrDquoteContent;
                        }
                    }
                }
                State::SArrSquote => {
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.mark();
                            state = State::SArrSquoteContent;
                        }
                        _ => {
                            self.emit(Event::Error { message: "expected quote", span: Span::new(self.pos, self.pos) });
                            state = State::SArrayValue;
                        }
                    }
                }
                State::SArrSquoteContent => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed string", span: Span::new(self.pos, self.pos) });
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b'\'' => {
                            self.emit(Event::QuotedStringValue { value: self.term(), span: self.span_from_mark() });
                            self.advance();
                            state = State::SArrayValue;
                        }
                        b'\\' => {
                            self.advance();
                            state = State::SArrSquoteEsc;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
                State::SArrSquoteEsc => {
                    if self.eof() {
                        self.emit(Event::Error { message: "unclosed string", span: Span::new(self.pos, self.pos) });
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        _ => {
                            self.advance();
                            state = State::SArrSquoteContent;
                        }
                    }
                }
                State::SArrBare => {
                    if self.eof() {
                        self.emit_typed_value();
                        state = State::SChildren;
                    }
                    match self.peek().unwrap() {
                        b' ' | b'\t' | b'\n' => {
                            self.emit_typed_value();
                            state = State::SArrayValue;
                        }
                        b']' => {
                            self.emit_typed_value();
                            self.emit(Event::ArrayEnd { span: Span::new(self.pos, self.pos) });
                            state = State::SAttrAfterValue;
                        }
                        _ => {
                            self.advance();
                        }
                    }
                }
            }
        }
    }

}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_empty_input() {
        let mut parser = Parser::new(b"");
        let events = parser.parse();
        assert!(events.is_empty());
    }

    #[test]
    fn test_comment() {
        let mut parser = Parser::new(b"; this is a comment\n");
        let events = parser.parse();
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], Event::Comment { .. }));
    }

    #[test]
    fn test_text() {
        let mut parser = Parser::new(b"hello world\n");
        let events = parser.parse();
        assert_eq!(events.len(), 1);
        assert!(matches!(events[0], Event::Text { .. }));
    }
}
